-- Supabase Postgres Schema for Product Feedback System

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    role TEXT DEFAULT 'user',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    category TEXT DEFAULT 'General',
    status TEXT DEFAULT 'Live',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    feedback_text TEXT NOT NULL,
    rating INTEGER CHECK(rating >= 1 AND rating <= 5),
    helpful_votes INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insert Demo Data
INSERT INTO users (username, password, role) VALUES ('admin', 'admin', 'admin') ON CONFLICT DO NOTHING;

INSERT INTO products (name, description, category, status) VALUES 
('Lumina AI Keyboard', 'A predictive typing assistant using advanced LLM integration directly onto your physical keyboard interface.', 'Hardware', 'In-Progress'),
('NexSync Cloud', 'Ultra-fast serverless file syncing optimized for large media and 3D rendering workflows.', 'Software', 'Live'),
('Nexus Watch App', 'A companion fitness and health application integrating with Nexus smart devices.', 'App', 'Planned'),
('Evo Drone X', 'Next-generation aerial drone with automated mapping features.', 'Hardware', 'Live'),
('CodeAssist IDE', 'Blazing fast code editor with AI debugging capabilities.', 'Software', 'In-Progress'),
('Fitness Journey', 'Track your daily workouts, macros, and sleep health.', 'App', 'Live'),
('HoloLens Display', 'An augmented reality monitor replacement tool.', 'Hardware', 'Planned');
